{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.createCustomResource (eq .Release.Service "Tiller") -}}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
{{ $.Files.Get $path }}
---
{{- end }}
{{- end }}