{{- if and (eq .Release.Service "Tiller") .Values.prometheusOperator.enabled .Values.prometheusOperator.createCustomResource  -}}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
{{ $.Files.Get $path }}
---
{{- end }}
{{- end }}
