version: 2.1
orbs:
  architect: giantswarm/architect@5.11.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: "app-build-suite"
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "kube-prometheus-stack"
          explicit_allow_chart_name_mismatch: true
          ct_config: ".circleci/ct-config.yaml"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: "app-build-suite"
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kube-prometheus-stack"
          explicit_allow_chart_name_mismatch: true
          ct_config: ".circleci/ct-config.yaml"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

