version: 2.1
orbs:
  architect: giantswarm/architect@4.1.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "prometheus-operator-app"
          ct_config: ".circleci/ct-config.yaml"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "prometheus-operator-app"
          ct_config: ".circleci/ct-config.yaml"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "prometheus-operator-app"
          ct_config: ".circleci/ct-config.yaml"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-prometheus-operator-to-shared-app-collection
          app_name: "prometheus-operator-app"
          app_namespace: "monitoring"
          app_collection_repo: "shared-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-prometheus-operator-to-aws-app-collection
          app_name: "prometheus-operator-app"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-prometheus-operator-to-azure-app-collection
          app_name: "prometheus-operator-app"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-prometheus-operator-to-kvm-app-collection
          app_name: "prometheus-operator-app"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-prometheus-operator-to-vmware-app-collection
          app_name: "prometheus-operator-app"
          app_namespace: "monitoring"
          app_collection_repo: "vmware-app-collection"
          disable_force_upgrade: true
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
