{{- if and  index .Values "prometheus-operator-app.prometheusOperator.enabled" index .Values "prometheus-operator-app.prometheusOperator.admissionWebhooks.enabled" index .Values "prometheus-operator-app.prometheusOperator.admissionWebhooks.patch.enabled" (not index .Values "prometheus-operator-app.prometheusOperator.admissionWebhooks.certManager.enabled") }}
{{- if $.Release.Namespace eq "kube-system" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-admission-create-network-policy
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
{{- include "kube-prometheus-stack.labels" $ | indent 6 }}
  egress:
  - {}
  ingress:
  - {}
  policyTypes:
  - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  labels:
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-patch
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-admission-patch-network-policy
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "kube-prometheus-stack.name" $ }}-admission-patch
{{- include "kube-prometheus-stack.labels" $ | indent 6 }}
  egress:
  - {}
  ingress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
{{- end }}