apiVersion: application.giantswarm.io/v1alpha1
kind: Chart
metadata:
  labels:
    app.kubernetes.io/name: prometheus-operator
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: managed
  name: prometheus-operator
spec:
  name: prometheus-operator
  namespace: monitoring
  config:
    configMap:
      name: prometheus-operator-app-chart-values
      namespace: giantswarm
    secret:
      name: prometheus-operator-app-chart-secrets
      namespace: giantswarm
  tarballURL: https://giantswarm.github.io/control-plane-test-catalog/prometheus-operator-{{ .Chart.Version }}.tgz
  version: {{ .Chart.Version }}
