apiVersion: v1
description: Provides easy monitoring definitions for Kubernetes services, and deployment and management of Prometheus instances.
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
engine: gotpl
maintainers:
  - name: vsliouniaev
  - name: bismarck
  - name: gianrubio
    email: gianrubio@gmail.com
  - name: yasn77
    email: yasser@giantswarm.io
  - name: ced0ps
    email: cedric@giantswarm.io
name: prometheus-operator-app
namespace: monitoring
sources:
  - https://raw.githubusercontent.com/giantswarm/prometheus-operator-app/v[[ .Version ]]/README.md
  - https://github.com/coreos/kube-prometheus
  - https://github.com/coreos/prometheus-operator
  - https://coreos.com/operators/prometheus
version: [[ .Version ]]
appVersion: 0.38.1
tillerVersion: ">=2.12.0"
home: https://github.com/giantswarm/prometheus-operator-app
keywords:
- operator
- prometheus
