apiVersion: v2
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
engine: gotpl
type: application
maintainers:
  - name: andrewgkew
    email: andrew@quadcorps.co.uk
  - name: bismarck
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: gianrubio
    email: gianrubio@gmail.com
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
  - name: GMartinez-Sisti
    email: kube-prometheus-stack@sisti.pt
  - name: scottrigby
    email: scott@r6by.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
name: prometheus-operator-app
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
version: 36.2.0
appVersion: 0.57.0
kubeVersion: ">=1.16.0-0"
home: https://github.com/giantswarm/prometheus-operator-app
keywords:
  - operator
  - prometheus
  - kube-prometheus
annotations:
  application.giantswarm.io/team: atlas
  "artifacthub.io/operator": "true"
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus

dependencies:
  - name: kube-state-metrics
    version: "4.9.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "3.3.*"
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.31.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
