apiVersion: v2
appVersion: "v0.60.1"
name: prometheus-operator-app
description: Giant Swarm's Prometheus Operator Deployment
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
version: 3.0.0
sources:
  - "https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack"
home: https://github.com/giantswarm/prometheus-operator-app
maintainers:
  - name: giantswarm/team-atlas
    email: team-atlas@giantswarm.io
annotations:
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
dependencies:
  - name: kube-prometheus-stack
    version: 43.2.1
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus-operator-app
