---
prometheus-operator-app:
  alertmanager:
    alertmanagerSpec:
      image:
        repository: docker.io/giantswarm/alertmanager
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  coreDns:
    service:
      selector:
        k8s-app: coredns
  grafana:
    ingress:
      ingressClassName: nginx
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    prometheusSpec:
      image:
        repository: docker.io/giantswarm/prometheus
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    thanosIngress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  prometheusOperator:
    enabled: true
    image:
      repository: docker.io/giantswarm/prometheus-operator
    labels:
      giantswarm.io/monitoring_basic_sli: "true"
    prometheusDefaultBaseImage: docker.io/giantswarm/prometheus
    verticalPodAutoscaler:
      enabled: true
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
        image:
          repository: docker.io/giantswarm/kube-webhook-certgen
          sha: ""
      certManager:
        enabled: false
    prometheusConfigReloader:
      image:
        repository: docker.io/giantswarm/prometheus-config-reloader
    thanosImage:
      repository: docker.io/giantswarm/thanos
    secretFieldSelector: "type!=helm.sh/release.v1"
