---
isManagementCluster: true

prometheus-operator-app:
  alertmanager:
    enabled: false
    alertmanagerSpec:
      image:
        repository: quay.io/giantswarm/alertmanager
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  coreDns:
    enabled: false
  defaultRules:
    create: false
  grafana:
    enabled: false
    rbac:
      pspUseAppArmor: false
    ingress:
      ingressClassName: nginx
  kubelet:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: false
    prometheusSpec:
      image:
        repository: quay.io/giantswarm/prometheus
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    thanosIngress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  prometheusOperator:
    enabled: true
    image:
      repository: quay.io/giantswarm/prometheus-operator
    podLabels: {}
    createCustomResource: false
    configReloaderCpu: 25m
    kubeletService:
      enabled: false
    prometheusDefaultBaseImage: quay.io/giantswarm/prometheus
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
        image:
          repository: quay.io/giantswarm/kube-webhook-certgen
          sha: ""
      certManager:
        enabled: false
    prometheusConfigReloader:
      image:
        repository: quay.io/giantswarm/prometheus-config-reloader
    thanosImage:
      repository: quay.io/giantswarm/thanos
    secretFieldSelector: "type!=helm.sh/release.v1"
