prometheus-operator-app:
  global:
    imageRegistry: docker.io
    rbac:
      create: true
      pspEnabled: true
  alertmanager:
    alertmanagerSpec:
      image:
        repository: giantswarm/alertmanager
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  coreDns:
    enabled: true
    # This PR fixes the coredns service as we use the `k8s-app: coredns` label
    service:
      selector:
        k8s-app: coredns
  grafana:
    rbac:
      pspEnabled: true
      pspUseAppArmor: false
    ingress:
      ingressClassName: nginx
  kubeApiServer:
    enabled: true
    serviceMonitor:
      relabelings:
      # Add app label.
      - targetLabel: app
        replacement: kubernetes
      metricRelabelings:
        # Keep from upstream values (https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-44.4.1/charts/kube-prometheus-stack/values.yaml#L967)
      - action: drop
        regex: apiserver_request_duration_seconds_bucket;(0.15|0.2|0.3|0.35|0.4|0.45|0.6|0.7|0.8|0.9|1.25|1.5|1.75|2|3|3.5|4|4.5|6|7|8|9|15|25|40|50)
        sourceLabels:
        - __name__
        - le
      # GS addition to reduce cardinality
      - action: drop
        regex: apiserver_request_slo_duration_seconds_bucket
        sourceLabels:
        - __name__
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: true
    service:
      port: 10257
      targetPort: 10257
      selector:
        component: kube-controller-manager
    serviceMonitor:
      https: true
      insecureSkipVerify: true
      relabelings:
      # Add app label.
      - targetLabel: app
        replacement: kube-controller-manager
      # Add node label.
      - sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: node

  kubeEtcd:
    enabled: true
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: true
    service:
      port: 10259
      targetPort: 10259
      selector:
        component: kube-scheduler
    serviceMonitor:
      https: true
      insecureSkipVerify: true
      relabelings:
      # Add app label.
      - targetLabel: app
        replacement: kube-scheduler
      # Add node label.
      - sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: node

  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    image:
      repository: giantswarm/kube-state-metrics
    verticalPodAutoscaler:
      enabled: true
    networkPolicy:
      enabled: true
      egress:
      - {}
      ingress:
      - {}
  nodeExporter:
    enabled: false
  prometheus-node-exporter:
    rbac:
      pspEnabled: true
  prometheus:
    prometheusSpec:
      image:
        repository: giantswarm/prometheus
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    thanosIngress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  prometheusOperator:
    enabled: true
    admissionWebhooks:
      patch:
        image:
          # We have 2 images for this: https://github.com/giantswarm/retagger/blob/dc815cbec228a32d7dc1859e6e3c73bef5488b52/images.yaml#L1069 and https://github.com/giantswarm/retagger/blob/dc815cbec228a32d7dc1859e6e3c73bef5488b52/images.yaml#L513
          # The jettech one is old and does not work with Kubernetes 1.22. We need to deprecate it later.
          repository: giantswarm/ingress-nginx-kube-webhook-certgen
    alertmanagerDefaultBaseImage: giantswarm/alertmanager
    image:
      repository: giantswarm/prometheus-operator
    labels:
      giantswarm.io/monitoring_basic_sli: "true"
    prometheusConfigReloader:
      image:
        repository: giantswarm/prometheus-config-reloader
    prometheusDefaultBaseImage: giantswarm/prometheus
    networkPolicy:
      enabled: true
    secretFieldSelector: "type!=helm.sh/release.v1"
    thanosImage:
      repository: giantswarm/thanos
    verticalPodAutoscaler:
      enabled: true
    serviceMonitor:
      relabelings:
      # Add app label.
      - sourceLabels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_name
        targetLabel: app
        # Add instance label.
      - sourceLabels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_instance
        targetLabel: instance
      # Add node label.
      - sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: node
      # Add team label.
      - sourceLabels:
        - __meta_kubernetes_pod_label_application_giantswarm_io_team
        targetLabel: team
  thanosRuler:
    enabled: false
    thanosRulerSpec:
      image:
        repository: giantswarm/thanos
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
