---
isManagementCluster: true
prometheusOperator:
  alertmanager:
    enabled: false
  coreDns:
    enabled: false
  defaultRules:
    create: false
  grafana:
    enabled: false
  kubelet:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    enabled: false
  prometheusOperator:
    createCustomResource: false
    configReloaderCpu: 25m
    kubeletService:
      enabled: false
    prometheusDefaultBaseImage: giantswarm/prometheus
    resources:
      limits:
        memory: 500Mi
      requests:
        memory: 250Mi
