---
grafana:
  enabled: true
prometheus-operator-app:
  global:
    rbac:
      create: true
      pspEnabled: true
  alertmanager:
    alertmanagerSpec:
      image:
        repository: docker.io/giantswarm/alertmanager
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  coreDns:
    service:
      selector:
        k8s-app: coredns
  grafana:
    # Embedded grafana disabled because GS managed grafana-app with custom conf is used instead
    enabled: false
    ingress:
      ingressClassName: nginx
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  prometheus:
    prometheusSpec:
      image:
        repository: docker.io/giantswarm/prometheus
    ingress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    ingressPerReplica:
      ingressClassName: nginx
      pathType: ImplementationSpecific
    thanosIngress:
      ingressClassName: nginx
      pathType: ImplementationSpecific
  prometheusOperator:
    enabled: true
    image:
      repository: docker.io/giantswarm/prometheus-operator
    prometheusDefaultBaseImage: docker.io/giantswarm/prometheus
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
        image:
          repository: docker.io/giantswarm/kube-webhook-certgen
          sha: ""
      certManager:
        enabled: false
    prometheusConfigReloader:
      image:
        repository: docker.io/giantswarm/prometheus-config-reloader
    thanosImage:
      repository: docker.io/giantswarm/thanos
    secretFieldSelector: "type!=helm.sh/release.v1"
