apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-operator.deployment-label-name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "prometheus-operator.deployment-label-annotation" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "prometheus-operator.deployment-label-name" . | quote }}
    {{- include "kube-prometheus-stack.selectorLabels" . | nindent 4 }}
    role: {{ include "prometheus-operator.deployment-label-selector" . | quote }}
