apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kube-prometheus-stack.crdUninstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-1"
    {{- include "kube-prometheus-stack.AnnotationsUninstall" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "kube-prometheus-stack.crdUninstall" . | quote }}
    {{- include "kube-prometheus-stack.selectorLabels" . | nindent 4 }}
    role: {{ include "kube-prometheus-stack.CRDInstallSelector" . | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "kube-prometheus-stack.crdUninstall" . | quote }}
        {{- include "kube-prometheus-stack.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube-prometheus-stack.crdInstall" . }}
      securityContext:
        runAsUser: {{ .Values.crds.securityContext.runAsUser }}
        runAsGroup: {{ .Values.crds.securityContext.runAsGroup }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kubectl
        image: "{{ .Values.image.registry }}/giantswarm/docker-kubectl:latest"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.

          kubectl delete -f /data/ 2>&1
        volumeMounts:
{{- range $path, $_ := .Files.Glob "crds/**" }}
        - name: {{ $path | base | trimSuffix ".yaml" }}
          mountPath: /data/{{ $path | base }}
          subPath: {{ $path | base }}
{{- end }}
      volumes:
{{ $currentScope := . }}
{{- range $path, $_ := .Files.Glob "crds/**" }}
    {{- with $currentScope }}
      - name: {{ $path | base | trimSuffix ".yaml" }}
        configMap:
          name: {{ include "kube-prometheus-stack.crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" }}
          items:
          - key: content
            path: {{ $path | base }}
{{- end }}
{{- end }}
      restartPolicy: Never
  backoffLimit: 4
