name: 'e2e-test: install chart on kind'
on: pull_request

jobs:
  test-install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0  

      - name: install chart
        run: |
          sed -i 's/\[\[ .Version \]\]/0.0.0/' helm/kube-prometheus-stack/Chart.yaml

          helm dependency update ./helm/kube-prometheus-stack/
      
          helm --kube-context kind-chart-testing install e2e-test-prometheus-operator ./helm/kube-prometheus-stack/ --wait

          kubectl --context kind-chart-testing wait pod --for=condition=Ready -l app=kube-prometheus-stack-operator

          sleep 120

          STATE=$(kubectl --context kind-chart-testing get pods -l app=kube-prometheus-stack-operator -ojson | jq -r '.items | .[0].status.phase')
          if [ "$STATE" == "Running" ]; then
              echo 'prometheus operator is Running'
          else
              echo 'Error prometheus operator is not Running' >&2
              exit 1
          fi
